import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const navPanelAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'nav-panel',
  parts: [
    { id: 'root', propertyProfile: 'layout', visualRole: 'panel', continuityGroup: 'nav-panel' },
    { id: 'content', visualRole: 'continuous-surface', continuityGroup: 'nav-panel' },
    { id: 'mainLayer', propertyProfile: 'layout', visualRole: 'continuous-surface', continuityGroup: 'nav-panel' },
    { id: 'sceneLayer', propertyProfile: 'layout', visualRole: 'continuous-surface', continuityGroup: 'nav-panel' },
    { id: 'sceneContent', visualRole: 'content', continuityGroup: 'nav-panel' },
    { id: 'brandHeader', visualRole: 'toolbar', continuityGroup: 'nav-panel' },
    { id: 'search', propertyProfile: 'control', visualRole: 'control' },
    { id: 'searchTrigger', propertyProfile: 'control', visualRole: 'control' },
    { id: 'topActions', visualRole: 'toolbar' },
    { id: 'topAction', propertyProfile: 'control', visualRole: 'control' },
    { id: 'extensionGroup', visualRole: 'content' },
    { id: 'sections', visualRole: 'content', continuityGroup: 'nav-panel' },
    { id: 'section', visualRole: 'content' },
    { id: 'sectionContent', visualRole: 'content' },
    { id: 'bottomBar', visualRole: 'toolbar', continuityGroup: 'nav-panel' },
    { id: 'miniAppFooter', visualRole: 'toolbar', continuityGroup: 'nav-panel' },
    { id: 'footer', visualRole: 'toolbar', continuityGroup: 'nav-panel' },
    { id: 'footerButton', propertyProfile: 'control', visualRole: 'control' },
    { id: 'footerMenu', propertyProfile: 'overlay', visualRole: 'popup' },
    { id: 'footerMenuItem', propertyProfile: 'control', visualRole: 'control' },
    { id: 'footerMenuDivider', propertyProfile: 'paint', visualRole: 'divider' },
    { id: 'workspaceMenu', propertyProfile: 'overlay', visualRole: 'popup' },
    { id: 'workspaceMenuItem', propertyProfile: 'control', visualRole: 'control' },
    { id: 'workspaceMenuDivider', propertyProfile: 'paint', visualRole: 'divider' },
    { id: 'workspaceMenuTitle', propertyProfile: 'paint', visualRole: 'content' },
    { id: 'workspaceMenuEmpty', visualRole: 'content' },
  ],
  facets: [
    { id: 'layer', attribute: 'data-bf-layer', values: ['main', 'scene'] },
    { id: 'action', attribute: 'data-bf-action', values: ['code', 'cowork', 'assistant', 'extensions', 'agents', 'skills'] },
    { id: 'section', attribute: 'data-bf-section', values: ['assistant-sessions', 'workspace'] },
  ],
  states: [
    { id: 'scene', selector: { kind: 'self', suffix: '[data-bf-state~="scene"]' } },
    { id: 'split', selector: { kind: 'self', suffix: '[data-bf-state~="split"]' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-bf-state~="active"]' } },
    { id: 'open', selector: { kind: 'self', suffix: '[data-bf-state~="open"]' } },
    { id: 'closing', selector: { kind: 'self', suffix: '[data-bf-state~="closing"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-bf-state~="empty"]' } },
  ],
};
