import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance/types';

export const skillsAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'skills',
  parts: [
    { id: 'root' }, { id: 'header' }, { id: 'tabs' }, { id: 'tab' }, { id: 'tabDivider' },
    { id: 'content' }, { id: 'installed' }, { id: 'sidebar' }, { id: 'sidebarHeader' },
    { id: 'sidebarTitle' }, { id: 'sidebarNav' }, { id: 'sidebarItem' },
    { id: 'sidebarItemIcon' }, { id: 'sidebarItemLabel' }, { id: 'sidebarItemCount' },
    { id: 'sidebarFooter' }, { id: 'sidebarHint' }, { id: 'main' }, { id: 'toolbar' },
    { id: 'filterAction' }, { id: 'addAction' },
    { id: 'loading' }, { id: 'error' }, { id: 'empty' }, { id: 'list' }, { id: 'skeleton' },
    { id: 'installedCard' }, { id: 'installedCardTop' }, { id: 'installedCardIcon' },
    { id: 'installedCardInfo' }, { id: 'installedCardName' }, { id: 'installedCardDescription' },
    { id: 'installedCardMeta' }, { id: 'installedCardActions' }, { id: 'installedCardDelete' },
    { id: 'pagination' }, { id: 'pageButton' }, { id: 'pageInfo' },
    { id: 'discover' }, { id: 'discoverHero' }, { id: 'discoverHeroContent' },
    { id: 'discoverTitle' }, { id: 'discoverSubtitle' }, { id: 'discoverSearch' },
    { id: 'discoverContent' }, { id: 'resultsInfo' },
    { id: 'suite' }, { id: 'suiteHero' }, { id: 'suiteHeroCopy' }, { id: 'suiteHeroActions' },
    { id: 'suiteModeToolbar' }, { id: 'suiteModes' }, { id: 'suiteModeTab' },
    { id: 'suiteModeTabLabel' }, { id: 'suiteLoading' },
    { id: 'suiteSections' }, { id: 'suiteSection' }, { id: 'suiteSectionLabel' },
    { id: 'suiteGrid' }, { id: 'suiteGroupCard' }, { id: 'suiteGroupHead' },
    { id: 'suiteGroupTitleWrap' }, { id: 'suiteGroupTitleRow' }, { id: 'suiteGroupTitle' },
    { id: 'suiteGroupCount' }, { id: 'suiteGroupActions' }, { id: 'suiteSkills' },
    { id: 'suiteSkill' }, { id: 'suiteSkillName' }, { id: 'suiteSkillStatus' },
  ],
  facets: [
    { id: 'tab', attribute: 'data-bf-tab', values: ['installed', 'discover'] },
    { id: 'category', attribute: 'data-bf-category', values: ['all', 'builtin', 'user', 'project', 'suite'] },
    { id: 'level', attribute: 'data-bf-level', values: ['user', 'project'] },
    { id: 'mode', attribute: 'data-bf-mode', values: ['agentic', 'Cowork', 'Claw', 'Team'] },
  ],
  states: [
    { id: 'hover', selector: { kind: 'self', suffix: ':hover' } },
    { id: 'focusVisible', selector: { kind: 'self', suffix: ':focus-visible' } },
    { id: 'disabled', selector: { kind: 'self', suffix: ':disabled' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-bf-state~="active"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-bf-state~="empty"]' } },
    { id: 'shadowed', selector: { kind: 'self', suffix: '[data-bf-state~="shadowed"]' } },
    { id: 'builtin', selector: { kind: 'self', suffix: '[data-bf-state~="builtin"]' } },
    { id: 'enabled', selector: { kind: 'self', suffix: '[data-bf-state~="enabled"]' } },
    { id: 'dirty', selector: { kind: 'self', suffix: '[data-bf-state~="dirty"]' } },
    { id: 'covered', selector: { kind: 'self', suffix: '[data-bf-state~="covered"]' } },
  ],
};
