// Boundary rules for feature assembly and optional dependency ownership.

export const optionalDependencyFeatureOwnerRules = [
  {
    crateName: 'services-core',
    reason:
      'services-core optional implementation dependencies must stay behind their exact owner capability',
    dependencies: [
      { depName: 'anyhow', ownerFeatures: ['dispatch-workspace', 'lsp', 'workspace-runtime'] },
      { depName: 'async-trait', ownerFeatures: ['permission', 'workspace-runtime'] },
      { depName: 'base64', ownerFeatures: ['filesystem'] },
      { depName: 'bitfun-core-types', ownerFeatures: ['local-storage', 'lsp'] },
      { depName: 'bitfun-events', ownerFeatures: ['local-storage'] },
      { depName: 'bitfun-runtime-ports', ownerFeatures: ['permission', 'workspace-runtime'] },
      { depName: 'chrono', ownerFeatures: ['filesystem', 'local-storage'] },
      { depName: 'dunce', ownerFeatures: ['runtime-ownership', 'workspace-identity', 'workspace-runtime'] },
      { depName: 'fs2', ownerFeatures: ['local-storage', 'runtime-ownership'] },
      { depName: 'git2', ownerFeatures: ['session-git'] },
      { depName: 'globset', ownerFeatures: ['workspace-instructions'] },
      { depName: 'ignore', ownerFeatures: ['filesystem'] },
      { depName: 'libc', ownerFeatures: ['local-storage', 'process-runtime'] },
      { depName: 'notify', ownerFeatures: ['lsp'] },
      { depName: 'rusqlite', ownerFeatures: ['permission'] },
      { depName: 'serde_yaml', ownerFeatures: ['markdown'] },
      {
        depName: 'sha2',
        ownerFeatures: [
          'dispatch-workspace',
          'filesystem',
          'local-storage',
          'runtime-ownership',
          'workspace-identity',
        ],
      },
      { depName: 'which', ownerFeatures: ['process-runtime'] },
      { depName: 'win32job', ownerFeatures: ['process-runtime'] },
      { depName: 'windows', ownerFeatures: ['local-storage', 'process-runtime'] },
      { depName: 'zip', ownerFeatures: ['lsp'] },
    ],
  },
  {
    crateName: 'runtime-ports',
    reason:
      'runtime-ports may expose product-domain permission ports only through the explicit permission contract slice',
    dependencies: [
      { depName: 'bitfun-product-domains', ownerFeatures: ['permission'] },
    ],
  },
  {
    crateName: 'core',
    reason:
      'bitfun-core product/runtime optional dependencies must stay owned by explicit feature gates',
    dependencies: [
      { depName: 'axum', ownerFeatures: ['product-full'] },
      { depName: 'bitfun-ai-adapters', ownerFeatures: ['ai-adapter-runtime'] },
      { depName: 'bitfun-agent-runtime', ownerFeatures: ['product-full'] },
      { depName: 'bitfun-agent-stream', ownerFeatures: ['product-full'] },
      { depName: 'bitfun-harness', ownerFeatures: ['product-full'] },
      { depName: 'bitfun-product-capabilities', ownerFeatures: ['product-capabilities'] },
      { depName: 'bitfun-product-domains', ownerFeatures: ['product-domains'] },
      { depName: 'bitfun-runtime-services', ownerFeatures: ['runtime-services'] },
      {
        depName: 'bitfun-services-integrations',
        ownerFeatures: [
          'announcement',
          'canvas-runtime',
          'file-watch',
          'git',
          'plugin-source',
          'product-domains',
          'product-full',
          'remote-workspace',
          'review-platform',
          'ssh-remote',
        ],
      },
      { depName: 'bitfun-tool-packs', ownerFeatures: ['tool-packs'] },
      { depName: 'chrono-tz', ownerFeatures: ['product-full'] },
      { depName: 'cron', ownerFeatures: ['product-full'] },
      { depName: 'dashmap', ownerFeatures: ['product-full'] },
      { depName: 'filetime', ownerFeatures: ['product-full'] },
      { depName: 'flate2', ownerFeatures: ['product-full'] },
      { depName: 'fs2', ownerFeatures: ['product-full'] },
      { depName: 'image', ownerFeatures: ['product-full', 'tool-packs'] },
      { depName: 'include_dir', ownerFeatures: ['product-full'] },
      { depName: 'indexmap', ownerFeatures: ['product-full'] },
      { depName: 'md5', ownerFeatures: ['product-full'] },
      { depName: 'reqwest', ownerFeatures: ['ai-adapter-runtime', 'product-full'] },
      { depName: 'rmcp', ownerFeatures: ['product-full'] },
      { depName: 'rusqlite', ownerFeatures: ['product-full'] },
      { depName: 'serde_yaml', ownerFeatures: ['workspace-runtime'] },
      { depName: 'similar', ownerFeatures: ['product-full'] },
      { depName: 'terminal-core', ownerFeatures: ['terminal'] },
      { depName: 'notify', ownerFeatures: ['lsp', 'workspace-watch'] },
      { depName: 'tokio-tungstenite', ownerFeatures: ['product-full'] },
      { depName: 'tower-http', ownerFeatures: ['product-full'] },
      { depName: 'tool-runtime', ownerFeatures: ['product-full'] },
    ],
  },
  {
    crateName: 'services-integrations',
    reason:
      'services-integrations optional runtime dependencies must stay owned by explicit integration features',
    dependencies: [
      { depName: 'aes', ownerFeatures: ['remote-connect'] },
      { depName: 'aes-gcm', ownerFeatures: ['mcp', 'remote-connect', 'remote-ssh-concrete'] },
      { depName: 'anyhow', ownerFeatures: ['browser-control', 'debug-log', 'mcp', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete'] },
      {
        depName: 'async-trait',
        ownerFeatures: ['git', 'mcp', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete', 'review-platform', 'script-tool-runtime', 'speech', 'workspace-search'],
      },
      {
        depName: 'base64',
        ownerFeatures: ['mcp', 'miniapp-runtime', 'remote-connect', 'remote-ssh-concrete', 'speech'],
      },
      { depName: 'bitfun-agent-runtime', ownerFeatures: ['deep-research', 'hook-import'] },
      { depName: 'bitfun-core-types', ownerFeatures: ['speech'] },
      { depName: 'bitfun-product-domains', ownerFeatures: ['canvas-runtime', 'function-agents', 'hook-import', 'miniapp-runtime', 'plugin-source'] },
      { depName: 'bitfun-runtime-ports', ownerFeatures: ['git', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete', 'script-tool-runtime'] },
      {
        depName: 'bitfun-services-core',
        ownerFeatures: ['browser-control', 'git', 'hook-import', 'mcp', 'miniapp-runtime', 'process-tree', 'remote-connect', 'remote-ssh', 'review-platform', 'workspace-search'],
      },
      { depName: 'bzip2', ownerFeatures: ['speech'] },
      { depName: 'chrono', ownerFeatures: ['debug-log', 'git', 'miniapp-market', 'remote-connect', 'remote-ssh-concrete', 'review-platform', 'speech'] },
      { depName: 'dirs', ownerFeatures: ['browser-control', 'miniapp-runtime', 'remote-connect', 'remote-ssh-concrete'] },
      { depName: 'dunce', ownerFeatures: ['plugin-source', 'workspace-search'] },
      { depName: 'fs2', ownerFeatures: ['plugin-source'] },
      { depName: 'futures', ownerFeatures: ['mcp', 'remote-connect', 'review-platform'] },
      { depName: 'futures-util', ownerFeatures: ['speech'] },
      { depName: 'git2', ownerFeatures: ['git'] },
      { depName: 'hex', ownerFeatures: ['hook-import', 'mcp', 'miniapp-market', 'plugin-source', 'remote-connect'] },
      { depName: 'hostname', ownerFeatures: ['remote-connect'] },
      { depName: 'image', ownerFeatures: ['remote-connect'] },
      { depName: 'local-ip-address', ownerFeatures: ['remote-connect'] },
      { depName: 'libc', ownerFeatures: ['plugin-source'] },
      { depName: 'mac_address', ownerFeatures: ['remote-connect'] },
      { depName: 'md5', ownerFeatures: ['remote-connect'] },
      { depName: 'notify', ownerFeatures: ['file-watch'] },
      { depName: 'oxc', ownerFeatures: ['canvas-runtime'] },
      { depName: 'qrcode', ownerFeatures: ['remote-connect'] },
      { depName: 'rand', ownerFeatures: ['mcp', 'remote-connect', 'remote-ssh-concrete'] },
      // remote-ssh-concrete: one-click relay deploy fetches the signed release
      // checksum over HTTPS and verifies it on this device, because the target
      // server has no minisign and no trust root of its own.
      { depName: 'reqwest', ownerFeatures: ['announcement', 'browser-control', 'debug-log', 'mcp', 'miniapp-market', 'miniapp-runtime', 'remote-connect', 'remote-ssh-concrete', 'review-platform', 'speech', 'web-tools'] },
      { depName: 'rmcp', ownerFeatures: ['mcp'] },
      { depName: 'russh', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'russh-keys', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'russh-sftp', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'rustls', ownerFeatures: ['remote-connect'] },
      { depName: 'rustls-native-certs', ownerFeatures: ['remote-connect'] },
      { depName: 'schannel', ownerFeatures: ['remote-connect'] },
      { depName: 'sha2', ownerFeatures: ['canvas-runtime', 'hook-import', 'mcp', 'miniapp-market', 'plugin-source', 'remote-connect', 'remote-ssh', 'review-platform', 'speech'] },
      { depName: 'sherpa-onnx', ownerFeatures: ['speech'] },
      { depName: 'shellexpand', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'sse-stream', ownerFeatures: ['mcp'] },
      { depName: 'ssh_config', ownerFeatures: ['remote-ssh-concrete', 'ssh_config'] },
      { depName: 'terminal-core', ownerFeatures: ['remote-ssh', 'remote-ssh-concrete'] },
      { depName: 'tar', ownerFeatures: ['speech'] },
      { depName: 'thiserror', ownerFeatures: ['browser-control', 'git', 'hook-import', 'miniapp-market', 'plugin-source', 'remote-ssh', 'remote-ssh-concrete', 'review-platform', 'speech', 'web-tools', 'workspace-search'] },
      { depName: 'tokio-tungstenite', ownerFeatures: ['remote-connect'] },
      { depName: 'tokio-util', ownerFeatures: ['remote-ssh', 'speech'] },
      { depName: 'urlencoding', ownerFeatures: ['canvas-runtime', 'miniapp-market', 'remote-connect', 'review-platform'] },
      { depName: 'uuid', ownerFeatures: ['canvas-runtime', 'debug-log', 'hook-import', 'miniapp-runtime', 'plugin-source', 'remote-connect', 'remote-ssh-concrete', 'speech'] },
      { depName: 'which', ownerFeatures: ['miniapp-runtime', 'remote-connect', 'script-tool-runtime', 'workspace-search'] },
      { depName: 'windows', ownerFeatures: ['plugin-source', 'review-platform'] },
      { depName: 'x25519-dalek', ownerFeatures: ['remote-connect'] },
    ],
  },
  {
    crateName: 'product-domains',
    reason:
      'product-domains optional runtime dependencies must stay owned by explicit product-domain features',
    dependencies: [
      { depName: 'dirs', ownerFeatures: ['miniapp'] },
      { depName: 'log', ownerFeatures: ['function-agents'] },
      { depName: 'hex', ownerFeatures: ['external-sources', 'miniapp', 'plugin-source'] },
      { depName: 'sha2', ownerFeatures: ['external-sources', 'miniapp', 'plugin-source'] },
      { depName: 'which', ownerFeatures: ['miniapp'] },
    ],
  },
];

export const coreProductFullFeatureAssemblyRule = {
  manifestPath: 'src/crates/assembly/core/Cargo.toml',
  featureName: 'product-full',
  requiredFeatureRefs: [
    'announcement',
    'dispatch-store',
    'file-watch',
    'filesystem',
    'git',
    'lsp',
    'local-storage',
    'process-runtime',
    'remote-workspace',
    'review-platform',
    'ssh-remote',
    'terminal',
    'workspace-runtime',
    'workspace-watch',
    'product-capabilities',
    'product-domains',
    'tool-packs',
  ],
  reason: 'bitfun-core product-full must explicitly assemble current owner feature groups',
};

export const coreClosedFeatureProfileRules = [
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'default',
    requiredFeatureRefs: [],
    exact: true,
    reason: 'services-core default profile must stay empty so consumers select capabilities explicitly',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'filesystem',
    requiredFeatureRefs: ['dep:base64', 'dep:chrono', 'dep:ignore', 'dep:sha2', 'tokio/fs'],
    exact: true,
    reason: 'services-core filesystem must own only local file operations and recursive search dependencies',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'local-storage',
    requiredFeatureRefs: [
      'dep:bitfun-core-types',
      'dep:bitfun-events',
      'dep:chrono',
      'dep:fs2',
      'dep:libc',
      'dep:sha2',
      'dep:windows',
      'tokio/fs',
      'tokio/sync',
      'windows/Win32_Foundation',
      'windows/Win32_Storage_FileSystem',
    ],
    exact: true,
    reason: 'services-core local-storage must own durable JSON, session, usage, and cleanup primitives',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'process-runtime',
    requiredFeatureRefs: [
      'dep:libc',
      'dep:which',
      'dep:win32job',
      'dep:windows',
      'tokio/io-util',
      'tokio/process',
      'windows/Win32_Foundation',
      'windows/Win32_System_Diagnostics_ToolHelp',
      'windows/Win32_System_Threading',
    ],
    exact: true,
    reason: 'services-core process-runtime must own command lookup and supervised child lifecycle dependencies',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-instructions',
    requiredFeatureRefs: ['dep:globset', 'tokio/fs', 'tokio/io-util'],
    exact: true,
    reason: 'services-core workspace-instructions must own declarative instruction glob expansion only',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'lsp',
    requiredFeatureRefs: [
      'dep:anyhow',
      'dep:bitfun-core-types',
      'dep:notify',
      'dep:zip',
      'process-runtime',
      'tokio/fs',
      'tokio/io-util',
      'tokio/sync',
    ],
    exact: true,
    reason: 'services-core lsp must compose process supervision with only its protocol and watcher capabilities',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-runtime',
    requiredFeatureRefs: [
      'dep:anyhow',
      'dep:async-trait',
      'dep:bitfun-runtime-ports',
      'dep:dunce',
      'process-runtime',
      'tokio/fs',
      'tokio/io-util',
      'tokio/sync',
    ],
    exact: true,
    reason: 'services-core workspace-runtime must compose process supervision with local workspace IO and ports',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'session-git',
    requiredFeatureRefs: ['local-storage', 'dep:git2'],
    exact: true,
    reason: 'services-core session-git must own only the libgit2-backed memory workspace capability',
  },
  {
    manifestPath: 'src/crates/services/services-core/Cargo.toml',
    featureName: 'workspace-identity',
    requiredFeatureRefs: ['dep:dunce', 'dep:sha2'],
    exact: true,
    reason: 'services-core workspace-identity must own only canonical workspace path identity support',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'dispatch-store',
    requiredFeatureRefs: ['local-storage'],
    exact: true,
    reason: 'bitfun-core dispatch-store must expose only the durable dispatch index facade',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'filesystem',
    requiredFeatureRefs: ['bitfun-services-core/filesystem'],
    exact: true,
    reason: 'bitfun-core filesystem must select only the concrete local filesystem owner',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'local-storage',
    requiredFeatureRefs: ['bitfun-services-core/local-storage'],
    exact: true,
    reason: 'bitfun-core local-storage must select only reusable local persistence owners',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'process-runtime',
    requiredFeatureRefs: ['bitfun-services-core/process-runtime'],
    exact: true,
    reason: 'bitfun-core process-runtime must select only managed process and local action owners',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'lsp',
    requiredFeatureRefs: ['dep:notify', 'bitfun-services-core/lsp'],
    exact: true,
    reason: 'bitfun-core lsp must select only the LSP owner and its workspace watcher dependency',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'terminal',
    requiredFeatureRefs: ['dep:terminal-core'],
    exact: true,
    reason: 'bitfun-core terminal must select only the standalone terminal service owner',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'workspace-runtime',
    requiredFeatureRefs: [
      'dep:serde_yaml',
      'filesystem',
      'local-storage',
      'process-runtime',
      'bitfun-services-core/markdown',
      'bitfun-services-core/workspace-identity',
      'bitfun-services-core/workspace-instructions',
      'bitfun-services-core/workspace-runtime',
    ],
    exact: true,
    reason: 'bitfun-core workspace-runtime must select only local workspace and runtime layout owners',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'workspace-watch',
    requiredFeatureRefs: ['workspace-runtime', 'dep:notify'],
    allowedTransitiveFeatureRefs: ['filesystem', 'local-storage', 'process-runtime'],
    exact: true,
    reason: 'bitfun-core workspace-watch must extend only local workspace runtime with identity watching',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'remote-workspace',
    requiredFeatureRefs: [
      'workspace-runtime',
      'dep:bitfun-services-integrations',
      'bitfun-services-integrations/remote-ssh',
    ],
    allowedTransitiveFeatureRefs: ['filesystem', 'local-storage', 'process-runtime'],
    exact: true,
    reason: 'bitfun-core remote-workspace must add only the remote workspace service surface',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'announcement',
    requiredFeatureRefs: ['bitfun-services-integrations/announcement'],
    exact: true,
    reason: 'bitfun-core announcement must select only the announcement owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'file-watch',
    requiredFeatureRefs: ['bitfun-services-integrations/file-watch'],
    exact: true,
    reason: 'bitfun-core file-watch must select only the file-watch owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'git',
    requiredFeatureRefs: ['bitfun-services-integrations/git'],
    exact: true,
    reason: 'bitfun-core git must select only the Git owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'review-platform',
    requiredFeatureRefs: ['bitfun-services-integrations/review-platform'],
    exact: true,
    reason:
      'bitfun-core review-platform must select only the review platform owner capability',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'service-integrations',
    requiredFeatureRefs: ['announcement', 'file-watch', 'git', 'review-platform'],
    exact: true,
    reason:
      'bitfun-core service-integrations is a compatibility facade group, not a product capability umbrella',
  },
  {
    manifestPath: 'src/crates/assembly/core/Cargo.toml',
    featureName: 'ssh-remote',
    requiredFeatureRefs: [
      'remote-workspace',
      'bitfun-services-integrations/remote-ssh-concrete',
    ],
    allowedTransitiveFeatureRefs: [
      'filesystem',
      'local-storage',
      'process-runtime',
      'workspace-runtime',
    ],
    exact: true,
    reason:
      'bitfun-core ssh-remote must extend only the remote workspace surface with concrete SSH and must not pull product Dispatch assembly',
  },
];

export const ownerCrateFeatureAssemblyRules = [
  {
    manifestPath: 'src/crates/execution/tool-provider-groups/Cargo.toml',
    reason: 'tool-packs must keep product feature groups explicit and default-light',
    requiredProductFullFeatures: [
      'basic',
      'git',
      'mcp',
      'browser-web',
      'computer-use',
      'image-analysis',
      'miniapp',
      'canvas',
      'agent-control',
    ],
  },
  {
    manifestPath: 'src/crates/services/services-integrations/Cargo.toml',
    reason: 'services-integrations must keep integration feature groups explicit and default-light',
    requiredProductFullFeatures: [
      'announcement',
      'browser-control',
      'canvas-runtime',
      'debug-log',
      'deep-research',
      'file-watch',
      'function-agents',
      'git',
      'hook-import',
      'miniapp-runtime',
      'mcp',
      'plugin-source',
      'remote-connect',
      'remote-ssh',
      'remote-ssh-concrete',
      'review-platform',
      'script-tool-runtime',
      'web-tools',
      'workspace-search',
    ],
  },
  {
    manifestPath: 'src/crates/contracts/product-domains/Cargo.toml',
    reason: 'product-domains must keep product domain feature groups explicit and default-light',
    requiredProductFullFeatures: ['plugin-source', 'miniapp', 'function-agents', 'external-sources'],
  },
];
