import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const reviewPlatformAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'review-platform',
  parts: [
    { id: 'root' },
    { id: 'chrome' },
    { id: 'brand' },
    { id: 'title' },
    { id: 'subtitle' },
    { id: 'actions' },
    { id: 'statusBar' },
    { id: 'statusLine' },
    { id: 'body' },
    { id: 'listPane' },
    { id: 'listToolbar' },
    { id: 'filters' },
    { id: 'listScroll' },
    { id: 'listItem' },
    { id: 'listItemMain' },
    { id: 'listItemTitle' },
    { id: 'listItemMeta' },
    { id: 'listItemStats' },
    { id: 'pagination' },
    { id: 'emptyState' },
    { id: 'errorState' },
    { id: 'loadingState' },
    { id: 'authGate' },
    { id: 'authCopy' },
    { id: 'authActions' },
    { id: 'detailPane' },
    { id: 'detailHeader' },
    { id: 'detailTitle' },
    { id: 'detailState' },
    { id: 'detailMeta' },
    { id: 'detailActions' },
    { id: 'facts' },
    { id: 'tabContent' },
    { id: 'section' },
    { id: 'sectionHeading' },
    { id: 'sectionActions' },
    { id: 'ciItem' },
    { id: 'ciHead' },
    { id: 'ciStatus' },
    { id: 'ciLog' },
    { id: 'thread' },
    { id: 'threadHead' },
    { id: 'threadBody' },
    { id: 'fileList' },
    { id: 'fileCard' },
    { id: 'fileRow' },
    { id: 'fileMain' },
    { id: 'fileStatus' },
    { id: 'filePath' },
    { id: 'fileDelta' },
    { id: 'diff' },
  ],
  facets: [
    { id: 'layout', attribute: 'data-bf-layout', values: ['full', 'detail'] },
  ],
  states: [
    { id: 'selected', selector: { kind: 'self', suffix: '[data-bf-state~="selected"]' } },
  ],
};
