import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const contentCanvasAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'content-canvas',
  parts: [
    { id: 'root', propertyProfile: 'layout', visualRole: 'workspace', continuityGroup: 'content-canvas' },
    { id: 'main', propertyProfile: 'layout', visualRole: 'continuous-surface', continuityGroup: 'content-canvas' },
    { id: 'editor', propertyProfile: 'layout', visualRole: 'continuous-surface', continuityGroup: 'content-canvas' },
    { id: 'anchorContent', visualRole: 'content', continuityGroup: 'content-canvas-anchor' },
    { id: 'anchor', propertyProfile: 'layout', visualRole: 'panel' },
    { id: 'anchorResizer' },
    { id: 'anchorHeader', visualRole: 'toolbar', continuityGroup: 'content-canvas-anchor' },
    { id: 'anchorTitle', propertyProfile: 'paint', visualRole: 'content' },
    { id: 'anchorActions', visualRole: 'toolbar' },
    { id: 'splitHandle', propertyProfile: 'control', visualRole: 'divider' },
    { id: 'dropZone', propertyProfile: 'overlay', visualRole: 'decoration' },
    { id: 'dropContent', visualRole: 'content' },
    { id: 'dropOverlay', propertyProfile: 'overlay', visualRole: 'decoration' },
    { id: 'dropTarget', propertyProfile: 'overlay', visualRole: 'decoration' },
    { id: 'dropIndicator', propertyProfile: 'overlay', visualRole: 'divider' },
    { id: 'empty', visualRole: 'content' },
    { id: 'emptyToolbar', visualRole: 'toolbar' },
    { id: 'emptyContent', visualRole: 'content' },
    { id: 'quickLook', propertyProfile: 'overlay', visualRole: 'popup' },
    { id: 'quickLookHeader', visualRole: 'toolbar', continuityGroup: 'content-canvas-quick-look' },
    { id: 'quickLookTitle', propertyProfile: 'paint', visualRole: 'content' },
    { id: 'quickLookActions', visualRole: 'toolbar' },
    { id: 'quickLookContent', visualRole: 'content', continuityGroup: 'content-canvas-quick-look' },
    { id: 'quickLookFooter', visualRole: 'toolbar', continuityGroup: 'content-canvas-quick-look' },
    { id: 'searchFilter', propertyProfile: 'control', visualRole: 'control' },
  ],
  facets: [
    { id: 'mode', attribute: 'data-bf-mode', values: ['agent', 'project', 'git', 'bottom-terminal'] },
    { id: 'direction', attribute: 'data-bf-direction', values: ['horizontal', 'vertical'] },
    { id: 'position', attribute: 'data-bf-position', values: ['left', 'right', 'top', 'bottom', 'center'] },
  ],
  states: [
    { id: 'active', selector: { kind: 'self', suffix: '[data-bf-state~="active"]' } },
    { id: 'maximized', selector: { kind: 'self', suffix: '[data-bf-state~="maximized"]' } },
    { id: 'resizing', selector: { kind: 'self', suffix: '[data-bf-state~="resizing"]' } },
    { id: 'collapsed', selector: { kind: 'self', suffix: '[data-bf-state~="collapsed"]' } },
    { id: 'dragging', selector: { kind: 'self', suffix: '[data-bf-state~="dragging"]' } },
    { id: 'open', selector: { kind: 'self', suffix: '[data-bf-state~="open"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-bf-state~="empty"]' } },
  ],
};
