import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const configAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'config',
  parts: [
    { id: 'root' },
    { id: 'content' },
    { id: 'contentInner' },
    { id: 'sectionStack' },
    { id: 'section' },
    { id: 'sectionHeader' },
    { id: 'sectionTitle' },
    { id: 'sectionDescription' },
    { id: 'sectionBody' },
    { id: 'row' },
    { id: 'rowLabel' },
    { id: 'rowDescription' },
    { id: 'rowControl' },
    { id: 'pageHeader' },
    { id: 'collectionSection' },
    { id: 'collectionItem' },
    { id: 'collectionRow' },
    { id: 'collectionMeta' },
    { id: 'collectionName' },
    { id: 'collectionControl' },
    { id: 'collectionDetails' },
    { id: 'collectionToolbar' },
    { id: 'collectionEditor' },
    { id: 'collectionFilters' },
    { id: 'collectionList' },
    { id: 'subagentModel' },
    { id: 'modelOption' },
    { id: 'modelSelection' },
    { id: 'modelSelectionOption' },
    { id: 'modelSelectionInput' },
    { id: 'modelSelectionLabel' },
    { id: 'modelSelectionDropdown' },
    { id: 'pageHeaderInner' },
    { id: 'pageHeaderInfo' },
    { id: 'pageHeaderTitle' },
    { id: 'pageHeaderSubtitle' },
    { id: 'pageHeaderExtra' },
  ],
  facets: [
    { id: 'align', attribute: 'data-bf-align', values: ['start', 'center'] },
    { id: 'layout', attribute: 'data-bf-layout', values: ['default', 'multiline', 'wide', 'balanced'] },
  ],
};
