import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const aiModelConfigAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'ai-model-config',
  parts: [
    { id: 'root' },
    { id: 'providerSelection' },
    { id: 'customOption' },
    { id: 'customOptionTitle' },
    { id: 'customOptionDescription' },
    { id: 'selectionDivider' },
    { id: 'providerSearch' },
    { id: 'providerList' },
    { id: 'providerRow' },
    { id: 'providerSelect' },
    { id: 'providerName' },
    { id: 'providerDescription' },
    { id: 'providerEmpty' },
    { id: 'providerMore' },
    { id: 'selectionActions' },
    { id: 'form' },
    { id: 'formBody' },
    { id: 'formActions' },
    { id: 'subscriptionArea' },
    { id: 'subscriptionNotice' },
    { id: 'subscriptionPanel' },
    { id: 'subscriptionSummary' },
    { id: 'subscriptionCode' },
    { id: 'subscriptionActions' },
    { id: 'collection' },
    { id: 'empty' },
    { id: 'providerGroup' },
    { id: 'providerGroupHeader' },
    { id: 'providerGroupTitle' },
    { id: 'providerGroupActions' },
    { id: 'providerGroupList' },
    { id: 'modelItem' },
    { id: 'modelMeta' },
    { id: 'modelActions' },
    { id: 'modelDetails' },
    { id: 'logoutConfirm' },
    { id: 'logoutActions' },
  ],
  facets: [
    { id: 'view', attribute: 'data-bf-view', values: ['selection', 'settings'] },
    { id: 'status', attribute: 'data-bf-status', values: ['starting', 'pending', 'cancelling', 'failed'] },
  ],
  states: [
    { id: 'hover', selector: { kind: 'self', suffix: ':hover' } },
    { id: 'expanded', selector: { kind: 'self', suffix: '[data-bf-state~="expanded"]' } },
    { id: 'disabled', selector: { kind: 'self', suffix: '[data-bf-state~="disabled"]' } },
  ],
};
