import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const componentPreviewAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'component-preview',
  parts: [
    { id: 'root' },
    { id: 'header' },
    { id: 'logo' },
    { id: 'headerActions' },
    { id: 'appearanceSelector' },
    { id: 'container' },
    { id: 'sidebar' },
    { id: 'sidebarHeader' },
    { id: 'sidebarToggle' },
    { id: 'navigation' },
    { id: 'category' },
    { id: 'main' },
    { id: 'componentHeader' },
    { id: 'emptyState' },
    { id: 'markdownRoot' },
    { id: 'markdownHeader' },
    { id: 'markdownControls' },
    { id: 'markdownStage' },
    { id: 'markdownEditor' },
    { id: 'columnRoot' },
    { id: 'columnNavigation' },
    { id: 'columnItem' },
    { id: 'columnPreview' },
    { id: 'demoRoot' },
    { id: 'demoCard' },
    { id: 'demoHeader' },
    { id: 'demoStage' },
    { id: 'demoFooter' },
    { id: 'fullPageRoot' },
    { id: 'fullPageTabs' },
    { id: 'fullPageTab' },
    { id: 'fullPageContent' },
    { id: 'gridRoot' },
    { id: 'gridCard' },
    { id: 'gridHeader' },
    { id: 'gridPreview' },
    { id: 'gridCanvas' },
    { id: 'gridInfo' },
    { id: 'largeCardRoot' },
    { id: 'largeCard' },
    { id: 'largeCardHeader' },
    { id: 'largeCardPreview' },
    { id: 'expandButton' },
  ],
  facets: [
    { id: 'columns', attribute: 'data-bf-columns', values: ['2', '3', '4'] },
  ],
  states: [
    { id: 'active', selector: { kind: 'self', suffix: '[data-bf-state~="active"]' } },
    { id: 'collapsed', selector: { kind: 'self', suffix: '[data-bf-state~="collapsed"]' } },
    { id: 'expanded', selector: { kind: 'self', suffix: '[data-bf-state~="expanded"]' } },
  ],
};
