fn main() {
    if std::env::var_os("CARGO_FEATURE_AGENT_RUNTIME").is_some() {
        emit_rerun_if_changed(std::path::Path::new("builtin_skills"));
        if let Err(e) = build_embedded_builtin_skills_metadata() {
            eprintln!("Warning: Failed to embed built-in skills metadata: {}", e);
        }
    }

    if std::env::var_os("CARGO_FEATURE_ANNOUNCEMENT").is_some() {
        if let Err(e) = embed_announcement_content() {
            eprintln!("Warning: Failed to embed announcement content: {}", e);
        }
    }
}

fn build_embedded_builtin_skills_metadata() -> Result<(), Box<dyn std::error::Error>> {
    use sha2::{Digest, Sha256};
    use std::fs;
    use std::io::Write;
    use std::path::{Path, PathBuf};

    fn collect_files(root: &Path, current: &Path, out: &mut Vec<PathBuf>) -> std::io::Result<()> {
        for entry in fs::read_dir(current)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                collect_files(root, &path, out)?;
            } else if path.is_file() {
                out.push(path.strip_prefix(root).unwrap_or(&path).to_path_buf());
            }
        }

        Ok(())
    }

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let builtin_root = Path::new(&manifest_dir).join("builtin_skills");

    println!("cargo:rerun-if-changed={}", builtin_root.display());
    emit_rerun_if_changed(&builtin_root);

    let mut files = Vec::new();
    if builtin_root.exists() {
        collect_files(&builtin_root, &builtin_root, &mut files)?;
    }
    files.sort();

    let mut hasher = Sha256::new();
    for relative_path in files {
        let normalized = relative_path.to_string_lossy().replace('\\', "/");
        hasher.update(normalized.as_bytes());
        hasher.update([0]);
        hasher.update(fs::read(builtin_root.join(&relative_path))?);
        hasher.update([0xff]);
    }
    let bundle_hash = format!("{:x}", hasher.finalize());

    let out_dir = std::env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("embedded_builtin_skills.rs");
    let mut file = fs::File::create(&dest_path)?;

    writeln!(
        file,
        "// Embedded built-in skills metadata (auto-generated by build.rs)"
    )?;
    writeln!(file, "// Do not edit manually.")?;
    writeln!(
        file,
        "pub const BUILTIN_SKILLS_BUNDLE_HASH: &str = \"{}\";",
        bundle_hash
    )?;

    Ok(())
}

fn escape_rust_string(s: &str) -> String {
    // To avoid quote issues, return the original string directly
    // Using r### syntax can include any character
    s.to_string()
}

fn emit_rerun_if_changed(path: &std::path::Path) {
    if !path.exists() {
        return;
    }

    println!("cargo:rerun-if-changed={}", path.display());

    if path.is_dir() {
        let entries = match std::fs::read_dir(path) {
            Ok(entries) => entries,
            Err(_) => return,
        };

        for entry in entries.flatten() {
            emit_rerun_if_changed(&entry.path());
        }
    }
}

/// Embed announcement MD content (tips + feature cards) from the content/ directory.
///
/// Scans `src/service/announcement/content/{tips,features}/{locale}/*.md` and generates
/// `embedded_announcements.rs` in OUT_DIR with a static HashMap keyed by
/// `"{type}/{locale}/{stem}"` (e.g. `"tips/zh-CN/vibe_describe_task"`).
fn embed_announcement_content() -> Result<(), Box<dyn std::error::Error>> {
    use std::collections::HashMap;
    use std::path::Path;

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let content_root = Path::new(&manifest_dir)
        .join("src")
        .join("service")
        .join("announcement")
        .join("content");

    println!("cargo:rerun-if-changed={}", content_root.display());
    emit_rerun_if_changed(&content_root);

    let mut entries: HashMap<String, String> = HashMap::new();

    for category in &["tips", "features"] {
        let cat_dir = content_root.join(category);
        if !cat_dir.exists() {
            continue;
        }
        for locale_entry in std::fs::read_dir(&cat_dir)?.flatten() {
            let locale_path = locale_entry.path();
            if !locale_path.is_dir() {
                continue;
            }
            let locale = locale_path
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .to_string();
            for file_entry in std::fs::read_dir(&locale_path)?.flatten() {
                let file_path = file_entry.path();
                if file_path.extension().and_then(|e| e.to_str()) != Some("md") {
                    continue;
                }
                let stem = file_path
                    .file_stem()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string();
                // Strip leading numeric prefix (e.g. "001_") to use bare id as key.
                let key_stem = if stem.len() > 4
                    && stem.chars().take(3).all(|c| c.is_ascii_digit())
                    && stem.chars().nth(3) == Some('_')
                {
                    stem[4..].to_string()
                } else {
                    stem
                };
                let key = format!("{}/{}/{}", category, locale, key_stem);
                let content = std::fs::read_to_string(&file_path)?;
                entries.insert(key, content);
            }
        }
    }

    generate_embedded_announcements_code(&entries)
}

fn generate_embedded_announcements_code(
    entries: &std::collections::HashMap<String, String>,
) -> Result<(), Box<dyn std::error::Error>> {
    use std::fs;
    use std::io::Write;
    use std::path::Path;

    let out_dir = std::env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("embedded_announcements.rs");
    let mut file = fs::File::create(&dest_path)?;

    writeln!(
        file,
        "// Embedded announcement content (auto-generated by build.rs)"
    )?;
    writeln!(file, "// Do not edit manually.")?;
    writeln!(file)?;
    writeln!(file, "use std::collections::HashMap;")?;
    writeln!(file, "use std::sync::LazyLock;")?;
    writeln!(file)?;
    writeln!(
        file,
        "pub static EMBEDDED_ANNOUNCEMENTS: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {{"
    )?;
    writeln!(file, "    let mut map = HashMap::new();")?;

    // Sort keys for deterministic generated output (see prompts codegen above).
    let mut sorted: Vec<(&String, &String)> = entries.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(b.0));
    for (key, content) in sorted {
        writeln!(
            file,
            "    map.insert(r###\"{}\"###, r###\"{}\"###);",
            escape_rust_string(key),
            escape_rust_string(content)
        )?;
    }

    writeln!(file, "    map")?;
    writeln!(file, "}});")?;
    writeln!(file)?;
    writeln!(
        file,
        "pub fn get_announcement_content(key: &str) -> Option<&'static str> {{"
    )?;
    writeln!(file, "    EMBEDDED_ANNOUNCEMENTS.get(key).copied()")?;
    writeln!(file, "}}")?;

    Ok(())
}
