**

!Cargo.toml
!Cargo.lock
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc

!src/
!src/**/
!src/**/Cargo.toml
!src/**/build.rs
!src/**/src/**
!src/crates/services/miniapp-market-service/migrations/**
!src/miniapp-market-web/**

**/node_modules
**/dist
!src/crates/contracts/product-domains/src/miniapp/builtin/assets/ppt-live/dist/
!src/crates/contracts/product-domains/src/miniapp/builtin/assets/ppt-live/dist/ui.bundle.js
**/target
src/mobile-web/dist
src/web-ui/public/monaco-editor
